# -*- coding: utf-8 -*-
"""Task1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YNXbBcfGa-KVDelB85VwmSoiA_GGiVbi
"""

import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
apps_df = pd.read_csv("/content/Playstore.csv")
# Filter for paid apps only
paid_apps = apps_df[apps_df["Price"] > 0].copy()

# Calculate revenue (Price * Maximum Installs)
paid_apps["Revenue"] = paid_apps["Price"] * paid_apps["Maximum Installs"]

# Plot scatter plot with trendline
plt.figure(figsize=(10, 6))
sns.scatterplot(data=paid_apps, x="Maximum Installs", y="Revenue", hue="Category", alpha=0.7, palette="tab10")

# Add trendline
sns.regplot(data=paid_apps, x="Maximum Installs", y="Revenue", scatter=False, color="black", line_kws={"linewidth": 1.5})

# Labels and title
plt.xscale("log")  # Log scale for better visualization
plt.yscale("log")
plt.xlabel("Number of Installs (log scale)")
plt.ylabel("Revenue (log scale)")
plt.title("Revenue vs. Installs for Paid Apps (by Category)")
plt.legend(title="Category", bbox_to_anchor=(1.01, 1), loc="upper left")

# Show the plot
plt.show()