# -*- coding: utf-8 -*-
"""Task3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15irimxtUviopDgI0pQuSa1EDRxt_aHOh
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Load datasets
data = pd.read_csv("/content/user review.csv")
playstore_data = pd.read_csv("/content/Playstore.csv")

# Merge datasets on 'App'
merged_data = pd.merge(data, playstore_data, on='App Name', how='inner')

# Filter for apps with more than 1,000 reviews and available sentiment data
filtered_data = merged_data.dropna(subset=['Sentiment'])
filtered_data = filtered_data[filtered_data['Reviews'] > 1000]

# Identify top 5 categories by total review count
top_categories = filtered_data.groupby('Category')['Reviews'].sum().nlargest(5).index
filtered_data = filtered_data[filtered_data['Category'].isin(top_categories)]

# Segment by rating groups
def rating_group(rating):
    if rating <= 2:
        return '1-2 Stars'
    elif 2 < rating <= 4:
        return '3-4 Stars'
    elif rating > 4:
        return '4-5 Stars'
    return 'Unknown'

filtered_data['Rating Group'] = filtered_data['Rating'].apply(rating_group)

# Compute sentiment distribution
sentiment_distribution = filtered_data.groupby(['Category', 'Rating Group'])['Sentiment'].value_counts(normalize=True).unstack().fillna(0)

# Visualization
plt.figure(figsize=(12, 6))
sentiment_distribution.plot(kind='bar', stacked=True, colormap='viridis', width=0.8)

plt.title('Sentiment Distribution by Rating Group (Top 5 Categories)')
plt.ylabel('Proportion of Reviews')
plt.xlabel('Category and Rating Group')
plt.legend(title='Sentiment', bbox_to_anchor=(1.05, 1), loc='upper left')
plt.xticks(rotation=45, ha='right')

plt.tight_layout()
plt.show()